export const projects = [{
    title: 'BLITZ',
    description: 'Developed a web application that let users with the help of a chatbot create their professional CV, enroll in online courses, and get courses, events, and job suggestions based on their skills (React, Node js, Express, MongoDB, Firebase, Dialogflow … )',
    image: '/images/home.jpg',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://blitz-assistant.herokuapp.com/',
    visit: 'https://github.com/Malek-Haddar/Elite-devs-Blitz-Chatbot',
    id: 0,
},
{
    title: 'I BLOG',
    description: "Iblog is a collective blog and the first inclusive platform in Tunisia. Read-hear-watch our content.I have an opinion, then I blog ..",
    image: '/images/i-blog.png',
    tags: ['Laravel', 'Voyager'],
    visit: 'https://github.com/Malek-Haddar/iBlog-Voyager',
    source: 'http://iblog.tn/',
    id: 1,
},
{
    title: 'Royal Car',
    description: 'Luxurious Car Agency application with Json Server (backend)',
    image: '/images/car.png',
    tags: ['Angular', 'Typescript'],
    visit: 'https://github.com/Malek-Haddar/Royal-Car_Angular-10',
    source: '#',
    id: 2,
},
{
    title: 'معلومة',
    description: "معلومة هو موقع عملتو منظمةأنا يقظ لمتابعة جميع مراحل الحصول على المعلومة وهذا لمتابعة مدى التزام الإدارة واحترامها لحقنا الدستوري في النفاذ إلى المعلومة وهو بدوره مساحة لنشر جميع المعلومات والوثائق المتحصل عليها عبر قانون عدد 22 لسنة 2016 مما يفتح المجال الى استعمالها",
    image: '/images/info.png',
    tags: ['Laravel', 'Bootstrap'],
    visit: 'https://github.com/Malek-Haddar/Ma3louma-Laravel',
    source: 'https://ma3louma.tn/',
    id: 3,
},
];

export const TimeLineData = [
    { year: 2016, text: 'Started my journey' },
    { year: 2019, text: 'got my license' },
    { year: 2019, text: 'Started my Software engineering cycle at ESPRIT' },
    { year: 2021, text: 'Passed 3 months internship in I-WATCH' },
    { year: 2022, text: 'Started my End of Study Project in I-WATCH' },
];